# Generated by Django 4.0 on 2022-04-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='User',
        ),
    ]
