# Generated by Django 4.0 on 2022-04-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='User',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='base.category'),
        ),
    ]
